import { formatDate } from './format';
import type { GymProfile, Membership, Payment } from './types';

type InvoiceMember = { id: number; membership_id: string; name: string; phone: string };

const money = (value: number) => new Intl.NumberFormat('en-IN', {
  style: 'currency', currency: 'INR', maximumFractionDigits: 2,
}).format(value);

function escapeHtml(value: string) {
  return value.replace(/[&<>"']/g, (character) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;',
  })[character] ?? character);
}

export function getMembershipInvoice(member: InvoiceMember, membership: Membership, payments: Payment[]) {
  if (membership.member_id !== member.id) throw new Error('This membership belongs to a different member.');
  const included = payments.filter((payment) => payment.member_id === member.id
    && payment.membership_id === membership.id && !payment.voided_at);
  const paidAmount = Math.round(included.reduce((sum, payment) => sum + payment.amount, 0) * 100) / 100;
  return {
    membership,
    payments: included,
    totalAmount: membership.total_amount,
    paidAmount,
    dueAmount: membership.status === 'cancelled' ? 0 : Math.max(0, Math.round((membership.total_amount - paidAmount) * 100) / 100),
  };
}

export function buildInvoiceHtml(gym: GymProfile, member: InvoiceMember, membership: Membership, payments: Payment[]) {
  const invoice = getMembershipInvoice(member, membership, payments);
  const rows = invoice.payments.map((payment) => `<tr><td>#${payment.id}</td><td>${escapeHtml(formatDate(payment.paid_at))}</td><td>${escapeHtml(payment.method)}</td><td class="amount">${money(payment.amount)}</td></tr>`).join('');
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>body{font-family:Arial,sans-serif;color:#0B1320;padding:32px;line-height:1.5}header{border-bottom:3px solid #08785A;padding-bottom:16px}h1{font-size:26px;margin:0}h2{font-size:20px}p{margin:5px 0}.muted{color:#687482}.summary{background:#F4F6F8;padding:18px;margin:20px 0}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:10px;border-bottom:1px solid #E5E9EE}.amount{text-align:right}.due{font-weight:700;font-size:20px}footer{margin-top:36px;font-size:11px;color:#687482}</style></head><body>
    <header><h1>${escapeHtml(gym.gymName)}</h1><p>${escapeHtml(gym.address)}</p><p>${escapeHtml([gym.phone, gym.email].filter(Boolean).join(' · '))}</p></header>
    <h2>Membership invoice</h2><p>${escapeHtml(member.name)} · ${escapeHtml(member.membership_id)}</p><p>+91 ${escapeHtml(member.phone)}</p>
    <div class="summary"><p><strong>${escapeHtml(membership.plan_name)}</strong> · Period #${membership.id}</p><p>${escapeHtml(formatDate(membership.start_date))} to ${escapeHtml(formatDate(membership.end_date))}</p><p>Status: ${escapeHtml(membership.status)}</p>
    <p>Plan amount: ${money(membership.base_amount)}</p><p>Discount: ${money(membership.discount_amount)}</p><p>Admission fee: ${money(membership.admission_fee)}</p><p>Total charges: ${money(invoice.totalAmount)}</p><p>Amount paid: ${money(invoice.paidAmount)}</p></div>
    <h2>Payments for this period</h2><table><thead><tr><th>Receipt</th><th>Date</th><th>Method</th><th class="amount">Amount</th></tr></thead><tbody>${rows || '<tr><td colspan="4">No payments recorded for this period.</td></tr>'}</tbody></table>
    <p class="amount due">Balance due: ${money(invoice.dueAmount)}</p>${membership.status === 'cancelled' ? '<p class="muted">This membership was cancelled. No outstanding payment is requested for this period.</p>' : ''}
    <footer>Only payments recorded for this membership period are included. Reversed entries are excluded. Generated by Pulse Fitness Manager.</footer></body></html>`;
}
