export const DEVELOPER_NAME = 'Abhishek Pundir';
export const SUPPORT_EMAIL = 'abhiyo13@gmail.com';
export const PRIVACY_UPDATED = '26 September 2026';

export const PRIVACY_SECTIONS = [
  { title: 'Your gym records stay on your phone', body: 'Pulse Fitness Manager stores gym details, membership plans, member contact details and optional profile information, photos, membership periods, payment records, attendance and expenses in the app’s private storage on your phone. You do not create an online account. We do not run a server that receives these gym records.' },
  { title: 'No ads, tracking or payment processing', body: 'This version has no advertising or analytics SDK, no automatic messaging and no integrated payment gateway. Cash, UPI, card and bank-transfer entries record payments handled outside the app. The app does not collect card credentials or process a transaction.' },
  { title: 'Permissions are optional where possible', body: 'Camera access is requested only when you choose to take a member photo. You can instead select a photo through Android’s system picker or keep a profile without one. Backup and import files are selected using Android’s file picker. Declining camera access does not prevent you from managing the gym.' },
  { title: 'You control exports and sharing', body: 'When you export a backup, invoice or member-list template, or open a WhatsApp reminder, the app sends the selected file or text only to the location or app you choose. Backups contain contact and financial records and available photos. They are not encrypted by Pulse Fitness Manager. Protect them and check the recipient before sharing. Other apps and storage providers handle the shared copy under their own policies.' },
  { title: 'Backups and phone replacement', body: 'Automatic Android cloud backup and device-transfer backup are disabled by this app’s configuration. Make verified manual backups regularly and keep a copy off the phone. Recovery copies created before a restore remain inside the app; they do not protect against losing the phone or uninstalling the app.' },
  { title: 'Retention and deletion', body: 'Records remain on your phone until you delete them or replace them through a confirmed restore. Deleting a member removes its related membership, payment and attendance records from the active database. Clearing app storage or uninstalling removes the app’s private files, including retained photo files, share caches and recovery copies. Copies you previously saved or sent outside the app must be deleted separately at their destination. We cannot recover records that exist only on your phone.' },
  { title: 'Protecting your records', body: 'The app uses Android’s private app storage and transaction-based database operations. It does not add a separate database password or backup encryption. Use your phone’s screen lock, keep Android updated and restrict access to exported files. The gym owner is responsible for entering appropriate member information and explaining its use to members.' },
  { title: 'Questions and policy changes', body: `Pulse Fitness Manager is developed by ${DEVELOPER_NAME}. For support or privacy questions, email ${SUPPORT_EMAIL}. Do not send member lists, financial records or backup files unless a specific support request requires them and you have permission to share them. If a future version adds cloud services or a payment gateway, its privacy information will be updated before those features are introduced.` },
] as const;
